# Generated by Django 4.0.1 on 2022-02-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=40, verbose_name='Игра')),
                ('second', models.CharField(max_length=200, verbose_name='Возраст')),
                ('full_text', models.TextField(verbose_name='Описание игры')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterField(
            model_name='rent',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='full_text',
            field=models.TextField(verbose_name='Комплектация'),
        ),
    ]
