 # Generated by Django 4.0.1 on 2022-02-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_game_rent_alter_rent_options_alter_rent_anons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus', models.CharField(max_length=50, verbose_name='Приемущества')),
                ('minus', models.CharField(max_length=50, verbose_name='Недостатки')),
                ('full_text', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('time', models.DateTimeField(verbose_name='Время публикации')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
