# Generated by Django 4.0.1 on 2022-02-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_kommet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kommet',
            name='time',
        ),
        migrations.AlterField(
            model_name='kommet',
            name='date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
