# Generated by Django 4.0.1 on 2022-04-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_kommet_time_alter_kommet_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consol', models.CharField(max_length=50, verbose_name='Консоль')),
                ('type_game', models.CharField(max_length=50, verbose_name='Тип игры')),
                ('about_game', models.TextField(verbose_name='О игре')),
            ],
            options={
                'verbose_name': 'Игры',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.AlterModelOptions(
            name='kommet',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
