# Generated by Django 4.0.1 on 2022-04-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_game_alter_kommet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kommet',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарий'},
        ),
    ]
