# Generated by Django 4.0.1 on 2022-04-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_kommet_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
