# Generated by Django 4.0.1 on 2022-04-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_game_delete_game_rent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
