# Generated by Django 4.0.1 on 2022-04-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consol', models.CharField(max_length=50, verbose_name='Consol')),
                ('about_game', models.CharField(max_length=50, verbose_name='na2ih')),
                ('set_game', models.CharField(max_length=50, verbose_name='janr')),
            ],
        ),
    ]
