# Generated by Django 4.0.1 on 2022-04-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
    ]
