# Generated by Django 4.0.1 on 2022-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_articles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='about_game',
            field=models.CharField(max_length=250, verbose_name='na2ih'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='set_game',
            field=models.TextField(max_length=999, verbose_name='janr'),
        ),
    ]
