# Generated by Django 4.0.4 on 2022-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_articles_about_game_alter_articles_set_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.CharField(max_length=50, verbose_name='Приставка')),
                ('game', models.CharField(max_length=50, verbose_name='5 любых игр из каталога')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес доставки(если требуется)')),
                ('days', models.CharField(max_length=50, verbose_name='Количество суток')),
                ('number', models.CharField(max_length=50, verbose_name='Телефон для связи ')),
                ('date_day', models.DateTimeField(verbose_name='Дата когда нужна приставка')),
                ('time', models.DateTimeField(verbose_name='Время когда нужна приставка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterField(
            model_name='kommet',
            name='plus',
            field=models.CharField(max_length=50, verbose_name='Преимущества'),
        ),
    ]
