# Generated by Django 4.0.4 on 2022-04-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_orders_alter_articles_options_alter_kommet_plus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Play_order',
        ),
    ]
