# Generated by Django 4.0.4 on 2022-05-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=50, verbose_name='Приставка')),
                ('gam', models.CharField(max_length=100, verbose_name='Адрес')),
                ('numbers', models.CharField(max_length=100, verbose_name='Адрес')),
                ('adres', models.CharField(max_length=100, verbose_name='Адрес')),
                ('time', models.CharField(max_length=100, verbose_name='Адрес')),
                ('wont', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
    ]
